backend:
  name: github
  repo: BSHSspeech
  branch: main # or 'master'

media_folder: "resources/images"
public_folder: "/resources/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
